### ISSUE TITLE
Sharelatex Problem

### ISSUE THREAD

**Issue by broomd** [novoid/LaTeX-KOMA-template#21]
Hey,

Since sharelatex is often used, it would be nice, if the template works also with it.
(Not possible to compile the current version)

Thanks a lot

**Comment by novoid** [comment]
I created an account on this cloud service and uploaded the current template.

Compiling worked but with three warnings that do not seem to be severe:

```
 Package hyperref Warning: Unexpected value for option `pdftex' is ignored on input line 4374.
 /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/hyperref.sty, line 4374

Package hyperref Warning: Values of option `pdfpagemode': * `UseNone' * `UseOutlines' * `UseThumbs' * `FullScreen' * `UseOC' (PDF 1.5) * `UseAttachments' (PDF 1.6) * An empty value disables the option. Unknown value `None' on input line 4374.
 /usr/local/texlive/2017/texmf-dist/tex/latex/hyperref/hyperref.sty

Package hyperref Warning: Option `pagecolor' is not available anymore.
```

Here is the downloaded result PDF which looks okay to me:

[KOMA_template.pdf](https://github.com/novoid/LaTeX-KOMA-template/files/1977546/KOMA_template.pdf)

So I'll close the bug here.

**Comment by broomd** [comment]
What did you excactly use? If I upload the whole GIT zip archiv, I get everytime I try to compile an out of time error :(
