### ISSUE TITLE
Another (simplified) template

### ISSUE THREAD

**Issue by niklasMayr** [novoid/LaTeX-KOMA-template#28]
Hello,

I m studying chemical engineering at the TU Graz, yet i m quite interessted in LaTeX. Still I - personally - found the given template rather confusing and therefore adapted it to my needs. In particular it features subfigures, a list of equations and a list abbreviations as well as usage examples.

If you are interessted I m willing to share it, indeptendently if you want to publish it or not.

All the best,
Niklas

**Comment by novoid** [comment]
Hello Niklas,
Thanks for your question - very much appreciated!
I absolutely understand your rationale. However, I try to keep the template as general as possible. Most people probably won't need subfigures or equations.
Therefore, I'm glad you asked and that you want to share your adaptations but I won't merge them to this general template in order to keep it as simple as possible (whatever that means for a template like this).
