### ISSUE TITLE
Extend Requirements section of README

### ISSUE THREAD

**Issue by dsalaj** [novoid/LaTeX-KOMA-template#34]
Maybe extending the Requirements section of README to include the required packages would be useful.
In order to just compile it for the first time on Ubuntu I had to install `texlive-bibtex-extra` and `texlive-lang-german`. And there is not much about requirements in the `Template-Documentation.pdf`.
An optimal solution would be something like `conda` environment `yml` file or something along those lines.
But just extending the README with a small list of essential latex packages that one can install would already be a huge help. Or even a one-liner:

    sudo apt install texlive-latex-extra texlive-bibtex-extra texlive-lang-german

Let me know if you like the suggestion. I could make a PR for the conda environment file.
And thanks for the template 👍

**Comment by novoid** [comment]
Hi,

This is very good input, you're referring to.

However, I don't know what conda is. Can you provide me a link?

For example, users of Windows MikTeX don't have to manually install anything at all because the LaTeX distro is installing missing requirements on-the-fly while compiling.

I'm not convinced that listing dependencies for all kind of LaTeX environments and operating systems is a good approach here. I also do have only two different hosts to test. Both are in productive use. Therefore, I would have to set up a series of virtual machines in order to find out about the manual dependency effort.

The target audience of the template is not a person that does not have LaTeX experience. At least a couple of years ago, installing biblatex was a major task, not very well supported. But I do understand that dependencies might be added in some form which I'm able to maintain in a sane way.

**Comment by novoid** [comment]
Closing this issue due to no update for almost a year.
